import React from 'react';

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <h2 className='text-center text-3xl font-bold my-25'>Hello About</h2>
        </div>
    );
};

export default page;