import Priv from '@/app/_com/page';
import React from 'react';

export const metadata = {
  title: {
    absolute: "My Files",
  },
  description: "Generated by create next app",
};

const page = async ({params}) => {
    const {filePath} = await params
    // console.log(filePath)
    return (
        <div>
          <Priv></Priv>
            <h2 className='text-center text-3xl font-bold my-25'>FIlePath -- {filePath?.join("/")}</h2>
        </div>
    );
};

export default page;